"""Offline source-declaration state-machine fixtures, never a live receipt.

Fresh browser context, every network request blocked, temporary data store.
The complete-flow fixtures stop after the final control is clicked and never
pretend that a platform publication succeeded.
"""
import asyncio
import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import AsyncMock, Mock, patch

from playwright.async_api import async_playwright

from publisher.browser import BrowserDriver, NeedsUser
from publisher.store import Store, now


ARTICLE = {
    'title': '创作来源流程测试', 'author': '', 'digest': '', 'body': '本地测试正文',
    'format': 'markdown', 'theme': 'jade', 'cover': '', 'source': 'import',
}
REMOTE = ('https://mp.weixin.qq.com/cgi-bin/appmsg?'
          't=media/appmsg_edit_v2&action=edit&type=77&appmsgid=fixture-draft&lang=zh_CN')
REAL_SLEEP = asyncio.sleep


class FixtureStopped(RuntimeError):
    """Expected local stop; no success receipt is generated by the fixture."""


class CreationSourceBrowserTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.store = Store(Path(self.temp.name))
        self.playwright = await async_playwright().start()
        self.browser = await self.playwright.chromium.launch(channel='msedge', headless=True)
        self.context = await self.browser.new_context()
        await self.context.route('**/*', lambda route: route.abort())
        self.page = await self.context.new_page()
        self.driver = self._driver()

    def _driver(self):
        driver = BrowserDriver(self.store)
        # The browser is about:blank throughout. Only the adapter's draft URL
        # property is represented here; this cannot navigate to an account.
        page = Mock(wraps=self.page)
        page.url = REMOTE + '&token=fixture'
        driver.page = page
        driver._account = AsyncMock()
        driver._prepare_publication_receipt = AsyncMock()
        return driver

    async def asyncTearDown(self):
        await self.browser.close()
        await self.playwright.stop()
        self.temp.cleanup()

    def _job(self, creation_source='unspecified', stage='draft_saved', status='running'):
        article = self.store.save_article({**ARTICLE, 'creation_source': creation_source})
        job = self.store.enqueue(article['id'], 'publish', now())
        self.store.update_job(job['id'], stage=stage, status=status, remote_url=REMOTE)
        self.driver.page_job_id = job['id']
        return self.store.job(job['id'])

    async def _fixture(self, *, prompt_sticky=False, form_sticky=False, custom_radios=False,
                       notice_skipped=False, initial_ai=False):
        prompt = '''<div class="weui-desktop-dialog" role="dialog">
            <h2>温馨提示</h2><p>建议主动声明创作来源。如内容由AI生成，请声明。</p>
            <a href="#" onclick="enterForm();return false">去声明</a>
            <a href="#" onclick="skipSource();return false">无需声明并发表</a></div>'''
        if custom_radios:
            choices = ''.join(
                '<div role="radio" aria-checked="false" tabindex="0" '
                'onclick="choose(this,\'%s\')">%s</div>' % (value, label)
                for value, label in (
                    ('current_affairs', '涉及时事信息'), ('medical', '涉及医疗健康'),
                    ('investment', '涉及投资理财'), ('ai', '内容由AI生成'),
                    ('non_ai', '无需声明')))
        else:
            choices = ''.join(
                '<label><input type="radio" name="source" value="%s" '
                'onchange="window.flow.choices.push(this.value)">%s</label>' % (value, label)
                for value, label in (
                    ('current_affairs', '涉及时事信息'), ('medical', '涉及医疗健康'),
                    ('investment', '涉及投资理财'), ('ai', '内容由AI生成'),
                    ('non_ai', '无需声明')))
        form = ('''<div class="weui-desktop-dialog" role="dialog">
            <h2>创作来源</h2><h3>声明类型</h3><div role="radiogroup">''' + choices + '''</div>
            <button onclick="confirmSource()">确认</button>
            <button onclick="window.flow.cancel++">取消</button></div>''')
        final = '''<div class="weui-desktop-dialog" role="dialog"><h2>发表确认</h2>
            <p>请确认文章已准备好</p><a href="#" onclick="window.flow.terminal++;return false">确认发表</a>
            <button onclick="window.flow.cancel++;render('')">取消</button></div>'''
        script = '''
            window.flow = {entry:0, go:0, openSettings:0, skip:0, choices:[], sourceConfirm:0, terminal:0, cancel:0};
            window.sourceDeclared = false;
            const promptMarkup = __PROMPT__, formMarkup = __FORM__, finalMarkup = __FINAL__;
            window.render = html => document.getElementById('dialogs').innerHTML = html;
            window.showPrompt = () => {
                window.flow.entry++;
                render(__NOTICE_SKIPPED__ || window.sourceDeclared ? finalMarkup : promptMarkup);
            };
            window.enterForm = () => { window.flow.go++; render(''); };
            window.openForm = () => { window.flow.openSettings++; render(formMarkup); };
            window.skipSource = () => { window.flow.skip++; if(!__PROMPT_STICKY__) render(finalMarkup); };
            window.confirmSource = () => {
                window.flow.sourceConfirm++;
                if(!__FORM_STICKY__) {
                    window.sourceDeclared = true;
                    document.getElementById('source-value').innerText =
                        window.flow.choices.at(-1) === 'ai' ? '内容由AI生成' : '无需声明';
                    render('');
                }
            };
            window.choose = (el, value) => {
                document.querySelectorAll('[role=radio]').forEach(node=>node.setAttribute('aria-checked','false'));
                el.setAttribute('aria-checked','true'); window.flow.choices.push(value);
            };
        '''
        for old, new in (
            ('__PROMPT__', json.dumps(prompt, ensure_ascii=False)),
            ('__FORM__', json.dumps(form, ensure_ascii=False)),
            ('__FINAL__', json.dumps(final, ensure_ascii=False)),
            ('__PROMPT_STICKY__', str(prompt_sticky).lower()),
            ('__FORM_STICKY__', str(form_sticky).lower()),
            ('__NOTICE_SKIPPED__', str(notice_skipped).lower()),
        ):
            script = script.replace(old, new)
        await self.page.set_content(
            '<input id="title" value="' + ARTICLE['title'] + '">'
            '<div class="ProseMirror" contenteditable="true" data-placeholder="正文">本地正文</div>'
            '<div id="source-row"><label>创作来源</label>'
            '<button id="source-value" class="js_claim_source_selected" onclick="openForm()">'
            + ('内容由AI生成' if initial_ai else '未添加') + '</button></div>'
            '<button id="publish" onclick="showPrompt()">发表</button><div id="dialogs"></div>'
            '<script>' + script + '</script>')

    async def _flow(self):
        return await self.page.evaluate('window.flow')

    async def _run_until_action(self, job, stop_counter='terminal', settled_polls=1):
        observations = 0

        async def no_receipt():
            nonlocal observations
            flow = await self._flow()
            if flow[stop_counter]:
                observations += 1
                if observations >= settled_polls:
                    raise FixtureStopped('local fixture stopped without publication receipt')
            return False

        async def yield_only(_):
            await REAL_SLEEP(0)

        self.driver._publish_signal = no_receipt
        with patch('publisher.browser.asyncio.sleep', new=yield_only):
            with self.assertRaises(FixtureStopped):
                await self.driver._publish(job)
        self.assertNotEqual(self.store.job(job['id'])['status'], 'published')
        self.assertEqual(self.store.job(job['id'])['article_url'], '')

    async def test_unknown_source_stops_before_source_or_publication_click(self):
        await self._fixture()
        job = self._job()
        with self.assertRaisesRegex(NeedsUser, '创作来源'):
            await self.driver._publish(job)
        flow = await self._flow()
        self.assertEqual(flow['entry'], 1)
        self.assertEqual([flow[key] for key in ('go', 'skip', 'sourceConfirm', 'terminal')], [0]*4)
        self.assertEqual(flow['choices'], [])
        result = self.store.job(job['id'])
        self.assertEqual((result['stage'], result['step']), ('source_required', 'creation_source'))
        self.assertNotEqual(result['status'], 'published')

    async def test_non_ai_uses_exact_skip_control_without_ai_form(self):
        await self._fixture()
        job = self._job('non_ai')
        await self._run_until_action(job)
        flow = await self._flow()
        self.assertEqual((flow['entry'], flow['skip'], flow['go'], flow['terminal']), (1, 1, 0, 1))
        self.assertEqual(flow['choices'], [])
        self.assertEqual(flow['sourceConfirm'], 0)

    async def test_ai_declaration_then_final_confirmation_each_happen_once(self):
        await self._fixture()
        job = self._job('ai')
        await self._run_until_action(job, settled_polls=3)
        flow = await self._flow()
        self.assertEqual((flow['entry'], flow['go'], flow['skip'], flow['sourceConfirm'], flow['terminal']),
                         (2, 1, 0, 1, 1))
        self.assertEqual(flow['openSettings'], 1)
        self.assertEqual(flow['choices'], ['ai'])
        self.assertEqual(flow['cancel'], 0)

    async def test_ai_custom_radio_controls_do_not_select_other_declarations(self):
        await self._fixture(custom_radios=True)
        job = self._job('ai')
        await self._run_until_action(job)
        flow = await self._flow()
        self.assertEqual(flow['choices'], ['ai'])
        self.assertEqual(flow['skip'], 0)
        self.assertEqual(flow['terminal'], 1)

    async def test_real_wechat_hidden_native_radio_uses_visible_label(self):
        await self._fixture()
        await self.page.add_style_tag(content='input[type=radio]{display:none}')
        job = self._job('ai')
        await self._run_until_action(job)
        flow = await self._flow()
        self.assertEqual(flow['choices'], ['ai'])
        self.assertEqual(flow['sourceConfirm'], 1)
        self.assertEqual(flow['terminal'], 1)

    async def test_ai_cookie_skips_notice_still_requires_ai_declaration_before_final(self):
        await self._fixture(notice_skipped=True)
        job = self._job('ai')
        await self._run_until_action(job, settled_polls=3)
        flow = await self._flow()
        self.assertEqual((flow['entry'], flow['go'], flow['cancel'], flow['openSettings']), (2, 0, 1, 1))
        self.assertEqual(flow['choices'], ['ai'])
        self.assertEqual((flow['sourceConfirm'], flow['terminal']), (1, 1))
        self.assertEqual(await self.page.locator('#source-value').inner_text(), '内容由AI生成')

    async def test_unknown_cookie_skips_notice_stops_without_final_or_source_selection(self):
        await self._fixture(notice_skipped=True)
        job = self._job()
        with self.assertRaisesRegex(NeedsUser, '创作来源'):
            await self.driver._publish(job)
        flow = await self._flow()
        self.assertEqual((flow['entry'], flow['cancel'], flow['openSettings']), (1, 1, 1))
        self.assertEqual((flow['sourceConfirm'], flow['terminal']), (0, 0))
        self.assertEqual(flow['choices'], [])
        self.assertEqual(self.store.job(job['id'])['stage'], 'source_required')

    async def test_non_ai_cookie_skips_notice_clears_previous_ai_label_before_final(self):
        await self._fixture(notice_skipped=True, initial_ai=True)
        job = self._job('non_ai')
        await self._run_until_action(job, settled_polls=3)
        flow = await self._flow()
        self.assertEqual((flow['entry'], flow['cancel'], flow['openSettings']), (2, 1, 1))
        self.assertEqual(flow['choices'], ['non_ai'])
        self.assertEqual((flow['sourceConfirm'], flow['terminal']), (1, 1))
        self.assertEqual(await self.page.locator('#source-value').inner_text(), '无需声明')

    async def test_persistent_skip_prompt_is_never_clicked_again(self):
        await self._fixture(prompt_sticky=True)
        job = self._job('non_ai')
        await self._run_until_action(job, stop_counter='skip', settled_polls=3)
        self.assertEqual((await self._flow())['skip'], 1)

    async def test_persistent_source_form_is_not_confirmed_or_selected_twice(self):
        await self._fixture(form_sticky=True)
        job = self._job('ai')
        await self._run_until_action(job, stop_counter='sourceConfirm', settled_polls=3)
        flow = await self._flow()
        self.assertEqual(flow['sourceConfirm'], 1)
        self.assertEqual(flow['choices'], ['ai'])
        self.assertEqual(flow['terminal'], 0)

    async def test_unknown_direct_source_form_does_not_guess_a_radio(self):
        await self._fixture()
        await self.page.evaluate('render(formMarkup)')
        with self.assertRaisesRegex(NeedsUser, '创作来源'):
            await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
        flow = await self._flow()
        self.assertEqual(flow['choices'], [])
        self.assertEqual(flow['sourceConfirm'], 0)

    async def test_declaration_option_requires_exact_text_and_uniqueness(self):
        for options in (
            '<label><input type="radio" name="source">内容由AI生成并同意协议</label>',
            '<label><input type="radio" name="source">内容由AI生成</label>'*2,
            '<label hidden><input type="radio" name="source">内容由AI生成</label>',
        ):
            with self.subTest(options=options):
                self.driver = self._driver()
                await self.page.set_content('<div role="dialog"><h2>创作来源</h2>'
                                            '<p>声明类型：请选择内容由AI生成或无需声明。</p>' + options +
                                            '<button onclick="window.confirms++">确认</button></div>')
                await self.page.evaluate('window.confirms=0')
                with self.assertRaises(NeedsUser):
                    await self.driver._publish_dialog_step(self.page.get_by_role('dialog'), 'ai')
                self.assertEqual(await self.page.evaluate('window.confirms'), 0)

    async def test_source_confirmation_restores_only_verified_original_draft(self):
        await self._fixture()
        await self.page.evaluate('render(promptMarkup)')
        job = self._job(stage='source_required', status='needs_review')
        await self.driver.confirm_creation_source(job, 'ai')
        result = self.store.job(job['id'])
        self.assertEqual((result['status'], result['stage'], result['step']), ('queued', 'draft_saved', 'saved'))
        self.assertEqual(result['snapshot']['creation_source'], 'ai')
        self.assertEqual(result['remote_url'], REMOTE)
        self.assertEqual(result['snapshot']['title'], ARTICLE['title'])
        self.assertEqual((await self._flow())['go'], 0)
        self.driver._account.assert_awaited()

    async def test_source_required_waiting_checkpoint_reopens_original_draft_after_restart(self):
        await self._fixture(notice_skipped=True)
        job = self._job(stage='source_required', status='waiting_user')
        self.driver.page_job_id = None
        # Do not navigate: represent reopening the already loaded offline
        # editor, then let its real DOM open the prerequisite source form.
        self.driver.page.goto = AsyncMock()
        await self.driver.confirm_creation_source(job, 'non_ai')
        self.driver.page.goto.assert_awaited_once_with(
            REMOTE + '&token=fixture', wait_until='domcontentloaded')
        result = self.store.job(job['id'])
        self.assertEqual((result['status'], result['stage']), ('queued', 'draft_saved'))
        self.assertEqual(result['snapshot']['creation_source'], 'non_ai')
        self.assertEqual(result['remote_url'], REMOTE)
        flow = await self._flow()
        self.assertEqual(flow['entry'], 0)
        self.assertEqual(flow['openSettings'], 1)
        self.assertEqual([flow[key] for key in ('go', 'skip', 'sourceConfirm', 'terminal')], [0]*4)

    async def test_legacy_publishing_requires_bound_current_session(self):
        await self._fixture()
        await self.page.evaluate('render(promptMarkup)')
        job = self._job(stage='publishing', status='needs_review')
        self.driver.page_job_id = None
        self.driver.page.goto = AsyncMock()
        with self.assertRaises(ValueError):
            await self.driver.confirm_creation_source(job, 'non_ai')
        self.driver.page.goto.assert_not_awaited()
        result = self.store.job(job['id'])
        self.assertEqual((result['status'], result['stage']), ('needs_review', 'publishing'))
        self.assertEqual(result['snapshot']['creation_source'], 'unspecified')
        self.assertEqual((await self._flow())['terminal'], 0)

    async def test_legacy_publishing_bound_to_source_prerequisite_can_confirm_source(self):
        await self._fixture()
        await self.page.evaluate('render(promptMarkup)')
        job = self._job(stage='publishing', status='needs_review')
        await self.driver.confirm_creation_source(job, 'non_ai')
        result = self.store.job(job['id'])
        self.assertEqual((result['status'], result['stage']), ('queued', 'draft_saved'))
        self.assertEqual(result['snapshot']['creation_source'], 'non_ai')
        flow = await self._flow()
        self.assertEqual([flow[key] for key in ('go', 'skip', 'sourceConfirm', 'terminal')], [0]*4)

    async def test_source_confirmation_rejects_wrong_page_job_without_changing_store(self):
        await self._fixture()
        await self.page.evaluate('render(promptMarkup)')
        job = self._job(stage='source_required', status='needs_review')
        self.driver.page_job_id = 'different-job'
        with self.assertRaises(ValueError):
            await self.driver.confirm_creation_source(job, 'non_ai')
        self.assertEqual(self.store.job(job['id'])['snapshot']['creation_source'], 'unspecified')
        self.assertEqual(self.store.job(job['id'])['status'], 'needs_review')

    async def test_source_confirmation_rejects_wrong_draft_id_without_changing_store(self):
        await self._fixture()
        await self.page.evaluate('render(promptMarkup)')
        job = self._job(stage='source_required', status='needs_review')
        self.driver.page.url = REMOTE.replace('fixture-draft', 'different-draft')
        with self.assertRaises(ValueError):
            await self.driver.confirm_creation_source(job, 'non_ai')
        self.assertEqual(self.store.job(job['id'])['snapshot']['creation_source'], 'unspecified')

    async def test_source_confirmation_rejects_wrong_title_or_account(self):
        for mismatch in ('title', 'account'):
            with self.subTest(mismatch=mismatch):
                self.driver = self._driver()
                await self._fixture()
                await self.page.evaluate('render(promptMarkup)')
                job = self._job(stage='source_required', status='needs_review')
                if mismatch == 'title':
                    await self.page.locator('#title').fill('另一篇文章')
                else:
                    self.driver._account = AsyncMock(side_effect=NeedsUser('账号不匹配'))
                with self.assertRaises(ValueError):
                    await self.driver.confirm_creation_source(job, 'non_ai')
                self.assertEqual(self.store.job(job['id'])['snapshot']['creation_source'], 'unspecified')

    async def test_source_confirmation_never_restores_unknown_final_publish_result(self):
        await self._fixture()
        await self.page.evaluate('render(finalMarkup)')
        job = self._job(stage='publishing', status='needs_review')
        with self.assertRaises(ValueError):
            await self.driver.confirm_creation_source(job, 'non_ai')
        self.assertEqual(self.store.job(job['id'])['stage'], 'publishing')
        self.assertEqual(self.store.job(job['id'])['status'], 'needs_review')

    async def test_source_confirmation_requires_saved_address_and_waiting_status(self):
        for change in ({'remote_url':''}, {'status':'published'}, {'status':'running'}, {'stage':'saving'}):
            with self.subTest(change=change):
                self.driver = self._driver()
                await self._fixture()
                await self.page.evaluate('render(promptMarkup)')
                job = self._job(stage='source_required', status='needs_review')
                self.store.update_job(job['id'], **change)
                job = self.store.job(job['id'])
                with self.assertRaises(ValueError):
                    await self.driver.confirm_creation_source(job, 'non_ai')
                self.assertEqual(self.store.job(job['id'])['snapshot']['creation_source'], 'unspecified')


if __name__ == '__main__':
    unittest.main()
