"""Offline notification fixtures, using the observed public editor markup.

All requests abort and data lives in a temporary Store. Final-click fixtures
stop without emitting a success receipt; they never prove real publication.
"""
import asyncio
import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import AsyncMock, Mock, patch

from playwright.async_api import async_playwright

from publisher.browser import BrowserDriver, NeedsUser
from publisher.store import Store, now


REAL_SLEEP = asyncio.sleep
REMOTE = ('https://mp.weixin.qq.com/cgi-bin/appmsg?'
          't=media/appmsg_edit_v2&action=edit&type=77&appmsgid=offline-notification')


class FixtureStopped(RuntimeError):
    """No platform publication receipt is generated by this fixture."""


class PublishNotificationTests(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.store = Store(Path(self.temp.name))
        self.playwright = await async_playwright().start()
        self.browser = await self.playwright.chromium.launch(channel='msedge', headless=True)
        self.context = await self.browser.new_context()
        await self.context.route('**/*', lambda route: route.abort())
        self.page = await self.context.new_page()
        self.driver = BrowserDriver(self.store)
        self.driver._prepare_publication_receipt = AsyncMock()
        self.driver.page = self.page

    async def asyncTearDown(self):
        await self.browser.close()
        await self.playwright.stop()
        self.temp.cleanup()

    def _switch(self, ident, title, row_class, *, checked=True, disabled=False,
                stuck=False, duplicate_input=False, duplicate_box=False):
        attrs = (' checked' if checked else '') + (' disabled' if disabled else '')
        element = ('<input id="%s" type="checkbox" class="weui-desktop-switch__input"%s>'
                   % (ident, attrs))
        box = ('<div class="weui-desktop-switch__box" '
               'onclick="window.flow.%s++"></div>' % ident)
        return ('<div class="publish_container %s weui-desktop-form__control-group">'
                '<label class="weui-desktop-form__label">%s</label>'
                '<div class="weui-desktop-form__controls"><div class="mass-send__timer-wrp">'
                '<label class="weui-desktop-switch weui-desktop-switch_loading"%s>%s%s</label>'
                '</div></div></div>' % (
                    row_class, title, ' onclick="event.preventDefault()"' if stuck else '',
                    element + (element.replace('id="' + ident + '"', 'id="duplicate-input"')
                               if duplicate_input else ''), box + (box if duplicate_box else '')))

    async def _fixture(self, *, checked=True, disabled=False, stuck=False,
                       duplicate_row=False, duplicate_input=False, duplicate_box=False,
                       no_notification_control=False):
        notify = ('<p>群发通知</p>' if no_notification_control else self._switch(
            'notify', '群发通知', 'mass_send__notify', checked=checked, disabled=disabled,
            stuck=stuck, duplicate_input=duplicate_input, duplicate_box=duplicate_box))
        if duplicate_row:
            notify += self._switch('notify_duplicate', '群发通知', 'mass_send__notify')
        neighbors = self._switch('group', '分组群发', 'mass_send__group') + self._switch(
            'timer', '定时发表', 'mass_send__timing')
        await self.page.set_content('''<style>
            .weui-desktop-switch__input { display:none }
            .weui-desktop-switch__box { display:inline-block; width:52px; height:28px; background:#eee }
            </style><div role="dialog">''' + notify + neighbors + '''
            <button onclick="window.flow.terminal++">发表</button></div>
            <script>window.flow={notify:0,notify_duplicate:0,group:0,timer:0,terminal:0}</script>''')

    async def _assert_neighbor_switches_untouched(self):
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['group'], flow['timer']), (0, 0))
        self.assertTrue(await self.page.locator('#group').is_checked())
        self.assertTrue(await self.page.locator('#timer').is_checked())

    async def test_custom_hidden_checkbox_is_disabled_before_single_final_click(self):
        await self._fixture()
        result = await self.driver._publish_dialog_step(self.page.get_by_role('dialog'), 'non_ai')
        self.assertEqual(result, 'submit')
        self.assertFalse(await self.page.locator('#notify').is_checked())
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['notify'], flow['terminal']), (1, 1))
        await self._assert_neighbor_switches_untouched()

    async def test_already_off_custom_switch_is_not_clicked(self):
        await self._fixture(checked=False)
        await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['notify'], flow['terminal']), (0, 1))
        self.assertFalse(await self.page.locator('#notify').is_checked())
        await self._assert_neighbor_switches_untouched()

    async def test_loading_class_is_not_used_as_checkbox_state(self):
        await self._fixture(checked=False)
        self.assertIn('loading', await self.page.locator('.mass_send__notify .weui-desktop-switch').get_attribute('class'))
        await self.driver._set_publish_notification(self.page.get_by_role('dialog'))
        self.assertEqual((await self.page.evaluate('window.flow'))['notify'], 0)

    async def test_stuck_custom_switch_stops_without_final_click_or_second_toggle(self):
        await self._fixture(stuck=True)
        with self.assertRaisesRegex(NeedsUser, '关闭状态未确认'):
            await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['notify'], flow['terminal']), (1, 0))
        self.assertTrue(await self.page.locator('#notify').is_checked())
        await self._assert_neighbor_switches_untouched()

    async def test_duplicate_rows_inputs_or_boxes_stop_before_any_final_click(self):
        for change in ({'duplicate_row': True}, {'duplicate_input': True}, {'duplicate_box': True}):
            with self.subTest(change=change):
                await self._fixture(**change)
                with self.assertRaises(NeedsUser):
                    await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
                flow = await self.page.evaluate('window.flow')
                self.assertEqual((flow['notify'], flow['notify_duplicate'], flow['terminal']), (0, 0, 0))
                await self._assert_neighbor_switches_untouched()

    async def test_disabled_custom_checkbox_stops_before_final(self):
        await self._fixture(disabled=True)
        with self.assertRaises(NeedsUser):
            await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['notify'], flow['terminal']), (0, 0))
        await self._assert_neighbor_switches_untouched()

    async def test_missing_notification_control_does_not_toggle_group_or_timer(self):
        await self._fixture(no_notification_control=True)
        with self.assertRaisesRegex(NeedsUser, '通知范围'):
            await self.driver._publish_dialog_step(self.page.get_by_role('dialog'))
        self.assertEqual((await self.page.evaluate('window.flow'))['terminal'], 0)
        await self._assert_neighbor_switches_untouched()

    async def test_semantic_checkbox_is_unchecked_and_read_back(self):
        for checked in (True, False):
            with self.subTest(checked=checked):
                await self.page.set_content('<div role="dialog"><label>群发通知<input id="notify" '
                                            'type="checkbox"' + (' checked' if checked else '') +
                                            ' onchange="window.toggles++"></label>'
                                            '<button onclick="window.terminal++">发表</button></div>'
                                            '<script>window.toggles=0;window.terminal=0</script>')
                self.assertEqual(await self.driver._publish_dialog_step(self.page.get_by_role('dialog')), 'submit')
                self.assertFalse(await self.page.locator('#notify').is_checked())
                self.assertEqual(await self.page.evaluate('window.toggles'), int(checked))
                self.assertEqual(await self.page.evaluate('window.terminal'), 1)

    async def test_persistent_final_dialog_is_never_submitted_twice(self):
        await self._fixture()
        final_markup = await self.page.get_by_role('dialog').evaluate('(el)=>el.outerHTML')
        await self.page.set_content('''<style>
            .weui-desktop-switch__input { display:none }
            .weui-desktop-switch__box { display:inline-block; width:52px; height:28px; background:#eee }
            </style><button id="initial">发表</button><div id="dialogs"></div>''')
        await self.page.evaluate('''markup=>{
            window.flow={notify:0,notify_duplicate:0,group:0,timer:0,terminal:0};
            document.getElementById('initial').onclick=()=>document.getElementById('dialogs').innerHTML=markup;
        }''', final_markup)
        wrapped = Mock(wraps=self.page)
        wrapped.url = REMOTE + '&token=fixture'
        self.driver.page = wrapped
        self.driver._account = AsyncMock()
        article = self.store.save_article({'title': '通知本地测试', 'body': '完整测试正文',
                                           'creation_source': 'non_ai'})
        job = self.store.enqueue(article['id'], 'publish', now())
        self.store.update_job(job['id'], stage='draft_saved', status='running', remote_url=REMOTE)
        job = self.store.job(job['id'])
        polls = 0

        async def no_receipt():
            nonlocal polls
            if (await self.page.evaluate('window.flow'))['terminal']:
                polls += 1
                if polls >= 3:
                    raise FixtureStopped('offline fixture, no success receipt')
            return False

        async def yield_only(_):
            await REAL_SLEEP(0)

        self.driver._publish_signal = no_receipt
        with patch('publisher.browser.asyncio.sleep', new=yield_only):
            with self.assertRaises(FixtureStopped):
                await self.driver._publish(job)
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['notify'], flow['terminal']), (1, 1))
        self.assertNotEqual(self.store.job(job['id'])['status'], 'published')
        self.assertEqual(self.store.job(job['id'])['article_url'], '')
        await self._assert_neighbor_switches_untouched()

    async def _notice_flow(self, *, sticky=False, marker='未开启群发通知', challenge=''):
        notice = ('<div role="dialog"><h2>发表</h2><p>' + marker + '，内容将展示在公众号主页。</p>'
                  '<p>' + challenge + '</p><button onclick="window.flow.terminal++;'
                  + ('' if sticky else "render('<p>等待平台响应</p>');")
                  + '">继续发表</button><button onclick="window.flow.cancel++">取消</button></div>')
        settings = ('<div role="dialog">' + self._switch('notify', '群发通知', 'mass_send__notify')
                    + '<button onclick="window.flow.settings++;render(noticeMarkup)">发表</button>'
                    '<button onclick="window.flow.cancel++">取消</button></div>')
        await self.page.set_content('''<style>
            .weui-desktop-switch__input { display:none }
            .weui-desktop-switch__box { display:inline-block; width:52px; height:28px; background:#eee }
            </style><button id="initial" onclick="window.flow.entry++;render(settingsMarkup)">发表</button>
            <div id="dialogs"></div><script>
            window.flow={entry:0,notify:0,settings:0,terminal:0,cancel:0};
            window.noticeMarkup=''' + json.dumps(notice, ensure_ascii=False) + ''';window.settingsMarkup='''
            + json.dumps(settings, ensure_ascii=False) + ''';
            window.render=html=>document.getElementById('dialogs').innerHTML=html;
            </script>''')
        wrapped = Mock(wraps=self.page)
        wrapped.url = REMOTE + '&token=fixture'
        self.driver.page = wrapped
        self.driver._account = AsyncMock()
        article = self.store.save_article({'title': '通知确认本地测试', 'body': '完整测试正文',
                                           'creation_source': 'non_ai'})
        job = self.store.enqueue(article['id'], 'publish', now())
        self.store.update_job(job['id'], stage='draft_saved', status='running', remote_url=REMOTE)
        return self.store.job(job['id'])

    async def _run_notice_until(self, job, counter):
        polls = 0

        async def no_receipt():
            nonlocal polls
            if (await self.page.evaluate('window.flow'))[counter]:
                polls += 1
                if polls >= 3:
                    raise FixtureStopped('offline notice fixture; no publication receipt')
            return False

        async def yield_only(_):
            await REAL_SLEEP(0)

        self.driver._publish_signal = no_receipt
        with patch('publisher.browser.asyncio.sleep', new=yield_only):
            with self.assertRaises(FixtureStopped):
                await self.driver._publish(job)
        self.assertNotEqual(self.store.job(job['id'])['status'], 'published')
        self.assertEqual(self.store.job(job['id'])['article_url'], '')

    async def test_settings_then_notification_notice_each_submit_once(self):
        job = await self._notice_flow()
        await self._run_notice_until(job, 'terminal')
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['entry'], flow['notify'], flow['settings'], flow['terminal']), (1, 1, 1, 1))
        self.assertEqual(flow['cancel'], 0)

    async def test_persistent_notification_notice_is_never_final_clicked_twice(self):
        job = await self._notice_flow(sticky=True)
        await self._run_notice_until(job, 'terminal')
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['settings'], flow['terminal']), (1, 1))
        self.assertEqual(await self.driver._publish_dialog_kind(self.page.get_by_role('dialog')),
                         'notification_notice')

    async def test_missing_exact_notification_marker_prevents_second_confirmation(self):
        job = await self._notice_flow(sticky=True, marker='已开启群发通知')
        await self._run_notice_until(job, 'settings')
        flow = await self.page.evaluate('window.flow')
        self.assertEqual((flow['settings'], flow['terminal']), (1, 0))
        self.assertEqual(await self.driver._publish_dialog_kind(self.page.get_by_role('dialog')), 'confirmation')

    async def test_notification_notice_with_authentication_or_protocol_stops_before_final(self):
        for challenge in ('扫码验证', '管理员验证', '验证码', '声明原创', '同意用户协议'):
            with self.subTest(challenge=challenge):
                job = await self._notice_flow(sticky=True, challenge=challenge)
                self.driver._publish_signal = AsyncMock(return_value=False)
                with self.assertRaisesRegex(NeedsUser, '本人验证|管理员扫码|声明'):
                    await self.driver._publish(job)
                flow = await self.page.evaluate('window.flow')
                self.assertEqual((flow['settings'], flow['terminal']), (1, 0))
                self.assertNotEqual(self.store.job(job['id'])['status'], 'published')


if __name__ == '__main__':
    unittest.main()
